config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get 'new' => 'charges#new'
  post 'checkout_payment' => 'charges#checkout_payment'
  resources :charges,:products#, only: [:new, :create]
  get 'express', to: 'products#express'
  get 'products/complete'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	 def paypal_url(return_url)

values = {
:business => email,
:cmd => '_cart',
:upload => 1,
:return => return_url,
#:invoice => UNIQUE_INTEGER
}

values.merge!({
"amount_1" => price,
"item_name_1" => name ,
"item_number_1" => id,
"quantity_1" => '1'
})

"https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	# before_action :authenticate_user!
	protect_from_forgery :except => :webhooks
	skip_before_action :verify_authenticity_token

  def index
  end
	def new
		if params[:product_id].present?
			@product = Product.find(params[:product_id])
		end
	end

	def checkout_payment
    begin

    @amount = Product.find(params[:product_id]).try(:price)
    customer = Stripe::Customer.create(
       :email => params[:stripeEmail],
       :source  => params[:stripeToken]
     )

    charge = Stripe::Charge.create(
       :customer    => customer.id,
       :amount      => @amount,
       :description => 'Rails Stripe customer',
       :currency    => 'usd'
     )

 rescue Stripe::CardError => e
     flash[:error] = e.message
     redirect_to new_charges_path
    end
  end
	def update
	redirect_to charges_path
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		 @products = Product.all
	end 
	def new
		@product = Product.new
	end 

	def create
			product = Product.new(product_params)
		if product.save
			 redirect_to product
		else
			render :new
		end
	end
	def edit 
		@product = Product.find(params[:id])
	end

	def update
		product = Product.find(params[:id])
		if product.update_attributes(product_params)
			redirect_to product
		else
			render :edit
		end
	end

	def show
		if params[:PayerID].present?
			redirect_to root_path
			# render :success
		else
			@product = Product.find(params[:id])
		end
	end

	def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
  end

  # def express
		# product = Product.find(params[:product_id])
 	# 	response = EXPRESS_GATEWAY.setup_purchase(product.try(:price).to_i,
		# ip: request.remote_ip,
		# return_url: url_for(:action => 'complete', :id => product.id),
		# cancel_return_url: "http://localhost:3000/products",
		# currency: "USD",
		# allow_guest_checkout: true,
		# items: [{name: product.try(:name), quantity: "1", amount: product.try(:price).to_i}]
		# )
		# redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
  # end

 #  def complete
	# 	product = Product.find(params[:product_id])
	#  begin
	# 	purchase = EXPRESS_GATEWAY.purchase(Product.find(params[:product_id]).try(:price),
	# 	:ip => request.remote_ip,
	# 	:payer_id => params[:PayerID],
	# 	:token => params[:token]
	# 	)
	# 	puts(purchase)
	#  rescue Exception => e
	# 	  logger.error "Paypal error while creating payment: #{e.message}"

	# 	  flash[:error] = e.message
	# end
	# 	unless purchase.success?
	# 	  flash[:error] = "Unfortunately an error occurred:" + purchase.message
	# 	else
	# 	  flash[:notice] = "Thank you for your payment"
	# 	end
	# 	  redirect_to products_path
 #  end

	private

	def product_params
		params.require(:product).permit(:name,:price,:avatar,:email)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/.index.html.erb
<h3>Thank you for shopping with us<h3>

app/views/charges/checkout_payment.html.erb
<p>You have successfully made payment of rs <%=@amount %></p>

app/views/charges/new.html.erb
<%= form_tag checkout_payment_path, method: :post do %>
    Grand Total : <%= @product.price %> $

    <%= hidden_field_tag :product_id, @product.id %>
    <script class="stripe-button" 
               data-amount="<%= @product.price.to_i*100 %>" 
               data-currency="inr" 
               data-email="<%=current_admin_user.email %>" 
               data-key="<%= Rails.configuration.stripe[:publishable_key] %>" 
               src="https://checkout.stripe.com/checkout.js">
    </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoActiveAdmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/.edit.html.erb
<%= form_for @product do |f|%>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :price %>
	<%= f.text_field :price %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :picture %>
	<%= f.file_field :avatar %>
	<%= f.submit "Update"%>
<%end%>

app/views/products/.new.html.erb
<%= form_for @product do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name  %><br>
  <%= f.label :price %>
  <%= f.text_field :price  %>
  <%= f.label :email %>
  <%= f.text_field :email  %>
  <%= f.label :pic %>
  <%= f.file_field :avatar  %>
<%= f.submit "create"%>
<%end%>

app/views/products/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!DOCTYPE html>
  <html lang="en" >
  <head>
    <meta charset="UTF-8">
    <title></title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>
        <link rel="stylesheet" href="css/style.css">
  </head>
    <body>
      <div id="pricing-table" class="clear">
    	<% @products.each do  |product|%>
        <div class="plan">
            <h3><%= product.name%><span><%= image_tag product.avatar.url , :size => "100x105"%></span></h3>
            <%=link_to "view", product_path(product),class: 'signup'  %>  
            <ul>
                <li><b>10 days</b> Replacement Policy</li>
                <li><b><%= product.price%></b> Price</li>
                <li><b><%= product.email%></b> Email</li>
                <li><b>10%</b> Discount</li>
                <li><b><%= product.description%></b> Description</li>
                <td><%= link_to(image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), product.paypal_url(product))%></td>
                <!-- <li><b><img id="myImage" onclick="changeImage()" src="/assets/1.png" width="50" height="50"></li> -->
            </ul> 
        </div>
        <%end%>
    </div>
       <!--  <script  src="js/index.js"></script>
        <script>
        function changeImage() {
          var image = document.getElementById('myImage');
          if (image.src.match("2.png")) {
            image.src = "/assets/1.png";
          } else {
            image.src = "/assets/2.png";
          }
        }
        </script> -->
    </body>
</html>

app/views/products/show.html.erb
<%= image_tag @product.avatar.url%><br>
<h1>  <%= @product.name%></h1><br>
<h1><%= @product.price%>₹</h1>
<h1><%= @product.email%>₹</h1>
<h3><%= link_to "Buy Now", new_charge_path(:product_id => @product.id), class: "add-to-cart btn btn-default" %></h3>
<h3><%= link_to "Pay Using PayPal ", express_path(:product_id => @product.id) %></h3>
<%#= link_to(image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), express_checkout_path)%>
<%#= link_to 'checkout', product.paypal_url(products_url) %> 

app/views/products/success.html.erb
success

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>